# Generated by Django 3.1.5 on 2021-01-23 11:24

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Librarian",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="libraryApp.user",
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
                ("address", models.TextField()),
                (
                    "sap_id",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("joined_on", models.DateField()),
            ],
            options={
                "verbose_name_plural": "Librarian",
            },
            bases=("libraryApp.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="libraryApp.user",
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
                ("address", models.TextField()),
                (
                    "sap_id",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("department", models.CharField(max_length=10)),
                ("grad_year", models.CharField(max_length=4)),
            ],
            options={
                "verbose_name": "Student",
            },
            bases=("libraryApp.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="libraryApp.user",
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
                ("address", models.TextField()),
                (
                    "sap_id",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("department", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Teacher",
            },
            bases=("libraryApp.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
