# Generated by Django 3.1.5 on 2021-02-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryApp", "0002_librarian_student_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=13)),
                ("name", models.CharField(max_length=30)),
                ("publisher", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=30)),
                ("publish_year", models.CharField(max_length=4)),
                ("quantity", models.IntegerField()),
                ("demand", models.BigIntegerField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Copy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=30)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryApp.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField()),
                ("return_date", models.DateField()),
                ("fine", models.IntegerField(default=0)),
                ("paid", models.BooleanField(default=False)),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryApp.copy",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryApp.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Issued Books",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_librarian",
            field=models.BooleanField(default=False, verbose_name="is librarian"),
        ),
        migrations.CreateModel(
            name="WaitingList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_alerted", models.BooleanField(default=False)),
                ("is_collected", models.BooleanField(default=False)),
                ("alerted_on", models.DateTimeField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryApp.book",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryApp.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryApp.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Waiting List",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification", models.CharField(max_length=50)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryApp.issue",
                    ),
                ),
                (
                    "waiting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryApp.waitinglist",
                    ),
                ),
            ],
        ),
    ]
