# Generated by Django 3.1.5 on 2021-01-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryApp", "0002_librarian_student_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("publisher", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=30)),
                ("publish_year", models.CharField(max_length=4)),
                ("quantity", models.IntegerField()),
                ("demand", models.BigIntegerField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
