# Generated by Django 3.1.5 on 2021-02-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryApp", "0003_auto_20210209_1207"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="copy",
            options={"verbose_name_plural": "Copies"},
        ),
        migrations.RemoveField(
            model_name="book",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="waitinglist",
            name="is_collected",
        ),
        migrations.AddField(
            model_name="copy",
            name="barcode",
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="libraryApp.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name="copy",
            name="condition",
            field=models.CharField(
                choices=[("BEST", "BEST"), ("GOOD", "GOOD"), ("WORST", "WORST")],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="libraryApp.student",
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="alerted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
