# Generated by Django 3.1.5 on 2021-02-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryApp", "0005_auto_20210213_1852"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="demand",
        ),
        migrations.RemoveField(
            model_name="copy",
            name="is_available",
        ),
        migrations.AlterField(
            model_name="issue",
            name="copy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issued",
                to="libraryApp.copy",
            ),
        ),
    ]
