# Generated by Django 3.1.1 on 2021-02-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryApp", "0006_auto_20210213_2323"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="subject",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="copy",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
