# Generated by Django 3.1.5 on 2021-03-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryApp", "0007_auto_20210218_1444"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="waiting",
        ),
        migrations.AddField(
            model_name="notification",
            name="nf_type",
            field=models.CharField(
                choices=[
                    ("FINE", "FINE"),
                    ("REMOVED", "REMOVED"),
                    ("ALLOTED", "ALLOTED"),
                    ("COLLECTED", "COLLECTED"),
                ],
                default=None,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="libraryApp.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issue",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
