# Generated by Django 3.1.5 on 2021-03-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryApp", "0008_auto_20210306_1541"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="libraryApp.book",
            ),
        ),
    ]
